### ISSUE TITLE
Opening a Python file adds and saves over cloud storage

### ISSUE THREAD

**Issue by neilccbrown** [k-pet-group/Strype#311]
If you have a project open that is saving to cloud storage, and you use "Open" to open a .py file, the resulting opened file is saved to the same cloud storage place, thus overwriting the project.  In fact, it also retains the previous code, it just adds the new code from the .py file alongside.  This seems surprising to me from an "Open" action; I think it should remove all existing code, then open the .py file, and not save over the cloud storage.

**Comment by PwtKCL** [comment]
Should blank the current code AND disconnect from Google Drive.
