### ISSUE TITLE
Update the cheat-sheet shortcut for function call to be clearer

### ISSUE THREAD

**Issue by neilccbrown** [k-pet-group/Strype#327]
In the meeting we discussed that the '␣' symbol for space was not well known and it may leave users unclear about how to enter a function call.  We decided we should spell out "Space" (perhaps in a slightly smaller font?) in the shortcut.  This will have the effect of widening that key, but that matches with space bar being a wide key on the keyboard.

**Comment by PwtKCL** [comment]
For the SPACE, we might want to show something that can be localised, as SPACE might not make sense for non-Engish speakers.

**Comment by PwtKCL** [comment]
I've used the small letter word "space" as a new indicator for English and French and Spanish. German is with a capital letter as it is a rule of the language, and checked with Michael for making sure that's the right word.
